[project]
name = "Phase_1"
version = "0.1.0"
description = "LangGraph project using uv"
authors = [{ name = "Aryan", email = "aryantandon2323@gmail.com" }]
requires-python = ">=3.10"

dependencies = [
  "langgraph",
  "langchain-openai",
  "langgraph-cli[inmem]"
]

[tool.uv]
# optional settings
